# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.srcs/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0.xci
# IP: The module: 'cpu_hdmi_system_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.gen/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_hdmi_system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.gen/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_hdmi_system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.srcs/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0.xci
# IP: The module: 'cpu_hdmi_system_mdm_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.gen/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_hdmi_system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.gen/sources_1/bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'cpu_hdmi_system_mdm_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
