# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constr/chipscope.xdc

# XDC: imports/constr/hdmi_top.xdc

# Block Designs: bd/cpu_hdmi_system/cpu_hdmi_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system || ORIG_REF_NAME==cpu_hdmi_system} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_microblaze_riscv_0_0/cpu_hdmi_system_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_microblaze_riscv_0_0 || ORIG_REF_NAME==cpu_hdmi_system_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_dlmb_v10_0/cpu_hdmi_system_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_dlmb_v10_0 || ORIG_REF_NAME==cpu_hdmi_system_dlmb_v10_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_ilmb_v10_0/cpu_hdmi_system_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_ilmb_v10_0 || ORIG_REF_NAME==cpu_hdmi_system_ilmb_v10_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_dlmb_bram_if_cntlr_0/cpu_hdmi_system_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_hdmi_system_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_ilmb_bram_if_cntlr_0/cpu_hdmi_system_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==cpu_hdmi_system_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_lmb_bram_0/cpu_hdmi_system_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_lmb_bram_0 || ORIG_REF_NAME==cpu_hdmi_system_lmb_bram_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_microblaze_riscv_0_axi_periph_0/cpu_hdmi_system_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==cpu_hdmi_system_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_mdm_1_0/cpu_hdmi_system_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_mdm_1_0 || ORIG_REF_NAME==cpu_hdmi_system_mdm_1_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_clk_wiz_1_0/cpu_hdmi_system_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_clk_wiz_1_0 || ORIG_REF_NAME==cpu_hdmi_system_clk_wiz_1_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_rst_clk_wiz_1_100M_0/cpu_hdmi_system_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==cpu_hdmi_system_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_axi_uartlite_0_0/cpu_hdmi_system_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_axi_uartlite_0_0 || ORIG_REF_NAME==cpu_hdmi_system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/cpu_hdmi_system/ip/cpu_hdmi_system_fir_coeff_bank_axi_0_2/cpu_hdmi_system_fir_coeff_bank_axi_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cpu_hdmi_system_fir_coeff_bank_axi_0_2 || ORIG_REF_NAME==cpu_hdmi_system_fir_coeff_bank_axi_0_2} -quiet] -quiet

# XDC: c:/Users/Balazs/Desktop/MSC1/FPGA/homework/HDMI_FIR_Homework.gen/sources_1/bd/cpu_hdmi_system/cpu_hdmi_system_ooc.xdc
